---
- name: Install Terraform on EC2 instance
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:

    # Install Terraform
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install unzip
      apt:
        name: unzip
        state: present

    - name: Unzip Terraform
      unarchive:
        src: "/home/aisha/jenkins/jenkins_project/terraform_1.8.2_linux_amd64.zip"
        dest: "/usr/local/bin/"

    - name: Set permissions for Terraform executable
      file:
        path: "/usr/local/bin/terraform"
        mode: "+x"

    # Install Jenkins
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Download Jenkins release repository configuration
      copy:
        src: /home/aisha/jenkins/jenkins_project/jenkins.io.key
        dest: /tmp/jenkins.io.key

    - name: Import Jenkins key
      apt_key:
        file: /tmp/jenkins.io.key

    - name: Add Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Update apt cache after adding repository
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: latest

    - name: Create jenkins user
      user:
        name: jenkins
        shell: /bin/bash
        system: yes

    - name: Create a directory if it does not exist
      file:
        path: /home/ubuntu/jenkins_home
        state: directory
        mode: '0777'

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
